name: Hello GitHub Actions

on:
  push:

jobs:
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Say Hello
        run: echo "Hello from GitHub Actions!"

      - name: Current Date and Time
        run: date

      - name: Print Branch Name
        run: 'echo "Branch: ${{ github.ref_name }}"'

      - name: List Repository Files
        run: ls -la

      - name: Print Operating System
        run: uname -a

      - name: Intentional Failure
        run: exit 1
